### ISSUE TITLE
Update meta data for NC screener

### ISSUE THREAD

**Issue by rickyctd** [Gary-Community-Ventures/benefits-calculator#1161]
Meta description for NC screener references CO, please update.

Ideal solution should read metadata from config object

![Screenshot 2024-07-09 at 2 11 24 PM](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/130072805/513993d7-687a-4df1-9457-33bb833f5665)
![Screenshot 2024-07-09 at 2 10 47 PM](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/130072805/e648396c-27ba-4d66-a642-c6a5923fdeba)

**Comment by Linda-Vu** [comment]
@Linda-Vu talk to Sydney about removing "colorado" from the metadata, because we cannot implement logic to change it.

**Comment by Linda-Vu** [comment]
@sydney-devine would you be okay with us removing "colorado" from the content in this html file? there wasn't an a simple way to complete this ticket / conditionally render it with logic since this file is in the root html and not JSX that we can manipulate. @CalebPena feel free to add your thoughts here too!

**Comment by sydney-devine** [comment]
@Linda-Vu I think that's fine.

**Comment by Linda-Vu** [comment]
@Mdemenko1 Sydney and Caleb gave the ok for you to remove Colorado from the metadata! let me know if you need anything else :)
