### ISSUE TITLE
Results Page Updates: Category Headings 

### ISSUE THREAD

**Issue by sydney-devine** [Gary-Community-Ventures/benefits-calculator#925]
**Desktop and Mobile - let's make the icons a little bigger? Especially on mobile some of them look really off. **

**Desktop - Heading Size - let's make headings a little larger on desktop? They get a bit lost right now since they're similarly sized to the card titles**

<img width="563" alt="image" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/5e21fed5-0ce5-4aa0-a676-2238ed22e263">

**Desktop and Mobile - Add more space between Icon and heading. It's really crammed next to each other right now.** 

<img width="457" alt="image" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/1df8bb79-9512-4495-b8cc-f69a22419ba2">

**Add padding after last program in each category so that there's space between the last card and the following category heading**

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/29f544b0-a553-471c-9a7c-6f19b4724994)

**Comment by ivonne-hernandez** [comment]
Good afternoon Carlos. I just chatted with @sydney-devine and suggested that we have the header and amount in their own block, left aligned so that there's more room for the header and icon. Let me know your thoughts or if you need any help with this.
<img width="547" alt="Category Header Edit" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/86989161/dce158a5-51de-4412-9d27-cb4d2f2e5c29">
